package protocol;

import java.io.Serializable;

public class GameStatsRequest implements Serializable {
    private String gameName;
    private String jobID;

    // Manager -> Master: no jobID yet
    public GameStatsRequest(String gameName) {
        this.gameName = gameName;
        this.jobID = null;
    }

    // Master -> Workers: includes jobID generated by Master
    public GameStatsRequest(String gameName, String jobID) {
        this.gameName = gameName;
        this.jobID = jobID;
    }

    public String getGameName() { return gameName; }
    public String getJobID() { return jobID; }
}
