package protocol;

import java.io.Serializable;

public class PlayerStatsRequest implements Serializable {
    private String playerId;
    private String jobID;

    // Manager -> Master: no jobID yet
    public PlayerStatsRequest(String playerId) {
        this.playerId = playerId;
        this.jobID = null;
    }

    // Master -> Workers: includes jobID generated by Master
    public PlayerStatsRequest(String playerId, String jobID) {
        this.playerId = playerId;
        this.jobID = jobID;
    }

    public String getPlayerId() {
        return playerId;
    }

    public String getJobID() {
        return jobID;
    }
}
