package protocol;
import java.io.Serializable;

public class ProviderStatsRequest implements Serializable {
    private String providerName;
    private String jobID;

    // Manager -> Master: no jobID yet
    public ProviderStatsRequest(String providerName) {
        this.providerName = providerName;
        this.jobID = null;
    }

    // Master -> Workers: includes jobID generated by Master
    public ProviderStatsRequest(String providerName, String jobID) {
        this.providerName = providerName;
        this.jobID = jobID;
    }

    public String getProviderName() {
        return providerName;
    }

    public String getJobID() { return jobID; }
}
