
package protocol;

import shared.Filters;

import java.io.Serializable;

public class SearchGamesRequest implements Serializable {
    private Filters filters;
    private String jobID;

    // Client (DummyPlayer) -> Master: no jobID yet
    public SearchGamesRequest(Filters filters) {
        this.filters = filters;
        this.jobID = null; //New
    }

    // Master -> Workers: includes jobID generated by Master
    public SearchGamesRequest(Filters filters, String jobID) {
        this.filters = filters;
        this.jobID = jobID;
    }

    public String getJobID() {
        return jobID;
    }

    public Filters getFilters() {
        return filters;
    }

}